name: Unreal CI (stub)

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'unreal-starter/**'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Placeholder
        run: echo "UE builds require a runner with the Engine installed. See README for self-hosted runner notes."
